force-app/main/default/objects/Function__mdt/Function__mdt.object-meta.xml
<CustomObject>
    <label>AI Function</label>
    <pluralLabel>AI Functions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Function__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Function_Property__mdt/Function_Property__mdt.object-meta.xml
<CustomObject>
    <label>AI Function Property</label>
    <pluralLabel>AI Function Properties</pluralLabel>
</CustomObject>

force-app/main/default/objects/Function_Property__mdt/fields/Enumerated_Values__c.field-meta.xml
<CustomField>
    <fullName>Enumerated_Values__c</fullName>
    <label>Enumerated Values</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Function_Property__mdt/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>AI Function</label>
    <referenceTo>Function__mdt</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/ChatInterface.cls
/* 
 * Author:      Anthony Wheeler(wheeler.anthony96@gmail.com)
 * Created:     2023-07-13
 * Description: Interfaces Salesforce objects with OpenAIs chat API
*/

public with sharing class ChatInterface {

    //Get Model name for given abbreviation
    private static String getModel(String modelAbbr){
        return [SELECT MasterLabel 
                FROM SetupAI__Model__mdt
                WHERE SetupAI__Abbreviation__c = :modelAbbr].MasterLabel;
    }

    //Retrieve defined functions and return them formatted
    private static ChatRequest.ChatFunction[] getFunctions(){
        ChatRequest.ChatFunction[] toReturn = new ChatRequest.ChatFunction[]{};
        for(Function__mdt func : [SELECT Id, MasterLabel, Description__c,
                                                (SELECT Id, MasterLabel, Description__c, Type__c, Enumerated_Values__c, Required__c
                                                FROM Properties__r)
                                            FROM Function__mdt]){
            toReturn.add(new ChatRequest.ChatFunction(func));
        }
        return toReturn;
    }

    //Submits Chat to API and returns response
    public static ChatRequest.ChatMessage chat(ChatRequest.ChatMessage[] messages, String model){
        //Construct request
        ChatRequest req = new ChatRequest(
            getModel(model == null ? 'gpt-3' : model),
            0,
            messages,
            getFunctions()
        );
        //Submit request
        ChatResponse res = OpenAI.chat(req);
        //Return response from assistant
        return res?.choices[0]?.message;
    }
  

}