force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Completion_Tokens__c.field-meta.xml
<CustomField>
    <fullName>Completion_Tokens__c</fullName>
    <label>Completion Tokens</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Function_Arguments__c.field-meta.xml
<CustomField>
    <fullName>Function_Arguments__c</fullName>
    <label>Function Arguments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Prompt_Tokens__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Tokens__c</fullName>
    <label>Prompt Tokens</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MessageConvertor.cls
/* 
 * Author:      Anthony Wheeler(wheeler.anthony96@gmail.com)
 * Created:     2023-07-19
 * Description: Converts Message__c records to ChatRequest.ChatMessage instances and vice versa
*/

public with sharing class MessageConvertor {
    
    //Convert records to classes
    public static ChatRequest.ChatMessage[] convert(Message__c[] messages){
        ChatRequest.ChatMessage[] toReturn = new ChatRequest.ChatMessage[]{};
        for(Message__c message : messages){
            toReturn.add(new ChatRequest.ChatMessage(message));
        }
        return toReturn;
    }

    //Convert records to classes
    public static Message__c convert(ChatRequest.ChatMessage message){
        return new Message__c(Role__c = message.role,
                              Content__c = message.content,
                              Completion_Tokens__c = message.completionTokens,
                              Prompt_Tokens__c = message.promptTokens,
                              Function_Name__c = message.function_call?.name,
                              Function_Arguments__c = message.function_call?.arguments);
    }

}